// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TomatoPizzaCafe.Data;

namespace TomatoPizzaCafe.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20181207183226_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TomatoPizzaCafe.Models.MakeYourOwn", b =>
                {
                    b.Property<string>("MakeYourOwnId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Crust");

                    b.Property<string>("Sauce");

                    b.Property<string>("Topping");

                    b.HasKey("MakeYourOwnId");

                    b.ToTable("MakeYourOwns");
                });

            modelBuilder.Entity("TomatoPizzaCafe.Models.Pizza", b =>
                {
                    b.Property<int>("PizzaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<double>("EightInchPrice");

                    b.Property<double>("EighteenInchPrice");

                    b.Property<double>("FourteenInchPrice");

                    b.Property<double>("TenInchPrice");

                    b.Property<double>("TwelveInchPrice");

                    b.Property<string>("Type");

                    b.HasKey("PizzaId");

                    b.ToTable("Pizzas");
                });
#pragma warning restore 612, 618
        }
    }
}
